### ISSUE TITLE
Parse data from a new controller

### ISSUE THREAD

**Issue by alari76** [Ardusensor/server_backend#31]
The new controller has a following data format: 

```
<11;336;838;343;33><11;336;838;343;34><13;28;164>

<SensorID; Temperature; Battery voltage; Humidity; Sendcounter>
```

Each package can consist of several sensor messages, and it always ends with a controller message (3 items) -

```
<ControllerID; GSM coverage; Battery voltage> 
```
- Temperature is calculated using a specific table. Will be updated later
- Battery voltage for sensor - multiply the number with \* 0.00384 to get exact voltage
- Humidity - store this number without modifications
- Sencounter is used to deduct the time of the reading. Each count equals to 30 minutes.
- GSM coverage - store this number without modifications. Scale is 0-31, where bigger number is better.
- Battery voltage for controller - it will have a different coefficient from the sensor. Initially just store this number without modifications.
- There might be a bug in the controller, where it sends garbage data after the closing '>'. Just ignore data that is located between '>' and '<'.

**Comment by alari76** [comment]
Garbaged data can be something like this - 

```
<11;335;838;343;200;59>><10;344;873;211;175>40>><10;344;871;211;177>41>><10;344;873;211;179>42>>~<13;23;200>
```

**Comment by alari76** [comment]
Please note that new protocol does not include timestamps, so we have to use server's clock to timestamp data.

**Comment by tanel** [comment]
Can you give me a couple of example packages? For test cases

**Comment by alari76** [comment]
```
<10;344;875;195;49>                <12;350;895;159;18>(34204)<10;344;875;195;49>                <12;350;895;159;18>(411279)<12;350;895;159;18>(525538)<13;347;888;195;57>(1101950)<17;343;883;159;51>(1229059)<16;145;379;159;17>(1253399)<11;338;879;287;16>(1416289)<15;345;1023;211;17>(1515808)<13;21;350>
```

**Comment by alari76** [comment]
```
<11;337;878;287;10>(117137)<13;23;179>
```

**Comment by alari76** [comment]
```
<13;347;886;199;51>(132207)<13;22;196>
```
