### ISSUE TITLE
Store controller data

### ISSUE THREAD

**Issue by alari76** [Ardusensor/server_backend#32]
Backend should be able to store timestamped data of controller's GSM coverage and battery voltage

**Comment by tanel** [comment]
How's the data coming in, in what format etc :)

**Comment by alari76** [comment]
Controller message (3 items) -

```
<ControllerID; GSM coverage; Battery voltage> 
```
- GSM coverage - store this number without modifications. Scale is 0-31, where bigger number is better.
- Battery voltage for controller - it will have a different coefficient from the sensor. Initially just store this number without modifications.
