### ISSUE TITLE
Backend features for temperature calibration

### ISSUE THREAD

**Issue by alari76** [Ardusensor/server_backend#46]
- Sensor readings can be off by some digits
- User can enter a current air temperature, which will be used by our server to calculate a calibration constant (CC)  CC = last sensor reading - current air temperature entered by user
- Later on, all temperatures are stored:
  - Original temperature with no calibration calculation
  - Calibrated temperature (CT) -> CT = sensor reading + CC
- UI will show only calibrated temperature

**Comment by tanel** [comment]
When new temperature is recorded, then calibration constant is re-calculated. however the old values will stay the same - the constant will be used only to save new values that are being added.
